/**
 * The brand palettes — the single source of truth for every colour the app
 * themes itself with, and for the colours the logo mark is drawn in.
 *
 * A palette carries ten brand tokens rather than a full UI palette. The 26 UI
 * variables are *derived* from those ten in `assets/themes.css` (generated by
 * `scripts/build-themes.mjs`), so adding a theme means picking ten colours,
 * not authoring twenty-six. Anything the derivation gets wrong for a specific
 * palette can be pinned via `pin`.
 *
 * Deliberately framework-free and value-import-free: `scripts/build-icon.cjs`
 * loads this file inside Electron through a one-shot esbuild transform, so it
 * must not pull in anything that isn't plain data.
 */

export type PaletteId =
  | 'arcane-gold'
  | 'ember-slate'
  | 'verdant-brass'
  | 'violet-ink'
  | 'midnight-cyan'
  | 'parchment-inverted'
  | 'steel-amber'
  | 'plum-mint'
  | 'phb'
  | 'light';

/** Light or dark ground. Drives the semantic colour step and `data-scheme`. */
export type Scheme = 'light' | 'dark';

/** The six roles the mark's shapes are painted with. */
export interface MarkRoles {
  back1: string;
  back2: string;
  front: string;
  dot: string;
  accent: string;
  bar2: string;
}

export interface BrandPalette {
  id: PaletteId;
  label: string;
  /** One line for the settings picker. */
  note: string;
  scheme: Scheme;
  /** "brand" palettes are the new set; "paper" are the two kept originals. */
  group: 'brand' | 'paper';

  // ---- the ten brand tokens ------------------------------------------------
  /** Ground behind the mark when it sits on its own tile (the app icon). */
  tile: string;
  /** The app background — and the ground the mark is composed against. */
  ground: string;
  back1: string;
  back2: string;
  front: string;
  dot: string;
  accent: string;
  bar2: string;
  text: string;
  textMuted: string;
  /**
   * The current-turn highlight. Deliberately NOT the accent: the accent marks
   * the active tab and primary buttons, and if whose-turn-it-is shared that
   * colour the busiest signal on the combat screen would stop standing out.
   */
  turn: string;

  /**
   * How the mark is painted when it sits directly on the theme's panel rather
   * than on its tile — light cards on a dark sidebar, dark cards on a light
   * one. This is the sidebar lock-up's role assignment.
   */
  on: MarkRoles;

  /** UI variables this palette overrides instead of deriving. */
  pin?: Record<string, string>;
}

/** The eight brand themes, then the two paper themes kept from before. */
export const PALETTES: BrandPalette[] = [
  {
    id: 'arcane-gold',
    label: 'Arcane gold',
    note: 'Deep violet stack, gold on the active turn',
    scheme: 'dark',
    group: 'brand',
    tile: '#F4EFE4', ground: '#1B1730', back1: '#5A52A0', back2: '#443C7E', front: '#2A2450',
    dot: '#8B84C4', accent: '#E0A33A', bar2: '#6B62A8',
    text: '#EFECFA', textMuted: '#A9A2D6', turn: '#A99BE8',
    on: { back1: '#443C7E', back2: '#8B84C4', front: '#EFECFA', dot: '#443C7E', accent: '#B7801F', bar2: '#8B84C4' },
  },
  {
    id: 'ember-slate',
    label: 'Ember slate',
    note: 'Cold slate, one ember',
    scheme: 'dark',
    group: 'brand',
    tile: '#EDEAE4', ground: '#1A1D21', back1: '#6E7783', back2: '#4A5058', front: '#2E333A',
    dot: '#9AA3AD', accent: '#E2603A', bar2: '#6E7783',
    text: '#EDF1F4', textMuted: '#98A2AC', turn: '#6EA8D8',
    on: { back1: '#4A5058', back2: '#8A929C', front: '#EDF1F4', dot: '#4A5058', accent: '#C24A26', bar2: '#8A929C' },
  },
  {
    id: 'verdant-brass',
    label: 'Verdant brass',
    note: 'Deep green field, brass fittings',
    scheme: 'dark',
    group: 'brand',
    tile: '#E9F0EA', ground: '#12261F', back1: '#3F7461', back2: '#2F5C4C', front: '#1C3E34',
    dot: '#7FB49B', accent: '#D9A441', bar2: '#4E8570',
    text: '#E6F1EA', textMuted: '#9FCBB6', turn: '#7FD4B0',
    on: { back1: '#2F5C4C', back2: '#7FB49B', front: '#E6F1EA', dot: '#2F5C4C', accent: '#B8892B', bar2: '#7FB49B' },
  },
  {
    id: 'violet-ink',
    label: 'Violet ink',
    note: 'Neutral near-black, arcane violet',
    scheme: 'dark',
    group: 'brand',
    tile: '#EFEDF2', ground: '#17161B', back1: '#6B5F86', back2: '#4A4160', front: '#26222F',
    dot: '#9C90B8', accent: '#A96AF5', bar2: '#6B5F86',
    text: '#ECEAF2', textMuted: '#9E98AC', turn: '#E0B341',
    on: { back1: '#4A4160', back2: '#9C90B8', front: '#ECEAF2', dot: '#4A4160', accent: '#8A4FD0', bar2: '#9C90B8' },
  },
  {
    id: 'midnight-cyan',
    label: 'Midnight cyan',
    note: 'Navy depth, cyan signal',
    scheme: 'dark',
    group: 'brand',
    tile: '#E8EDF2', ground: '#0F1E2B', back1: '#3C5877', back2: '#27405C', front: '#142639',
    dot: '#7FA0C0', accent: '#3FC8D9', bar2: '#3C5877',
    text: '#E4ECF3', textMuted: '#8FAEC9', turn: '#F2A81E',
    on: { back1: '#27405C', back2: '#7FA0C0', front: '#E4ECF3', dot: '#27405C', accent: '#199FB2', bar2: '#7FA0C0' },
  },
  {
    id: 'parchment-inverted',
    label: 'Parchment inverted',
    note: 'Cream cards on a dark table',
    scheme: 'dark',
    group: 'brand',
    tile: '#241F2E', ground: '#241F2E', back1: '#8A7F66', back2: '#C4B99E', front: '#F2E9D4',
    dot: '#8A7F66', accent: '#D4604E', bar2: '#C4B99E',
    text: '#F2E9D4', textMuted: '#B3A88E', turn: '#C4B99E',
    on: { back1: '#8A7F66', back2: '#C4B99E', front: '#F2E9D4', dot: '#8A7F66', accent: '#B5433A', bar2: '#C4B99E' },
    // the mark sits on cream there, where the darker brick still reads
  },
  {
    id: 'steel-amber',
    label: 'Steel amber',
    note: 'Blue-grey steel, amber warning light',
    scheme: 'dark',
    group: 'brand',
    tile: '#ECEEF0', ground: '#1B222B', back1: '#566575', back2: '#3B4757', front: '#232C38',
    dot: '#93A3B4', accent: '#F2A81E', bar2: '#566575',
    text: '#EAEFF4', textMuted: '#9BAABA', turn: '#93C3E4',
    on: { back1: '#3B4757', back2: '#93A3B4', front: '#EAEFF4', dot: '#3B4757', accent: '#C98209', bar2: '#93A3B4' },
  },
  {
    id: 'plum-mint',
    label: 'Plum and mint',
    note: 'Plum stack, mint highlight',
    scheme: 'dark',
    group: 'brand',
    tile: '#F0EBF2', ground: '#1E1226', back1: '#6B4677', back2: '#4E2F5A', front: '#2E1A38',
    dot: '#A588B0', accent: '#4FD3A0', bar2: '#6B4677',
    text: '#F1E9F4', textMuted: '#B9A0C3', turn: '#C79BD6',
    on: { back1: '#4E2F5A', back2: '#A588B0', front: '#F1E9F4', dot: '#4E2F5A', accent: '#17A97A', bar2: '#A588B0' },
  },

  // The two originals. Their UI values are pinned verbatim so they look
  // exactly as they always have; only the turn highlight changed, which used
  // to be the accent colour and therefore never stood out.
  {
    id: 'phb',
    label: 'PHB Style',
    note: 'Parchment and dark-red headings, like the official books',
    scheme: 'light',
    group: 'paper',
    tile: '#58180d', ground: '#eee5ce', back1: '#c9ad6a', back2: '#e0cfa6', front: '#f9f2e2',
    dot: '#8a7f66', accent: '#58180d', bar2: '#a08a63',
    text: '#23180f', textMuted: '#6f5b3e', turn: '#8a5a12',
    on: { back1: '#c9ad6a', back2: '#a08a63', front: '#58180d', dot: '#f9f2e2', accent: '#f2c14e', bar2: '#c9ad6a' },
    pin: {
      '--bg': '#eee5ce',
      '--bg-panel': '#fdf1dc',
      '--bg-panel-2': '#e9dbbd',
      '--row-hover': 'rgba(201, 173, 106, 0.18)',
      '--text': '#23180f',
      // Darker than the seed: the seed passed at 14px but this pin is what
      // 11-13px labels render in, and on parchment it needs the extra step.
      '--text-muted': '#5e4a30',
      '--accent': '#58180d',
      '--accent-dim': '#722f1e',
      '--danger': '#9c2b1b',
      '--danger-soft': '#9c2b1b',
      '--success': '#2f6b31',
      '--heal-color': '#2f6b31',
      '--pc-color': '#2a4b8d',
      '--monster-color': '#8a4b12',
      '--badge-bg': '#58180d',
      '--badge-border': '#c9ad6a',
      '--badge-text': '#f9ecd9',
      '--warn': '#8a5a12',
      '--miss': '#7a2c20',
      '--conc': '#5b3a86',
      '--font-ui': "'Book Antiqua', 'Palatino Linotype', Palatino, Georgia, serif",
    },
  },
  {
    id: 'light',
    label: 'Light',
    note: 'Plain light, for playing in daylight',
    scheme: 'light',
    group: 'paper',
    tile: '#1b1b1f', ground: '#f4f4f6', back1: '#6b6b76', back2: '#a1a1aa', front: '#f4f4f6',
    dot: '#6b6b76', accent: '#2563eb', bar2: '#a1a1aa',
    text: '#1b1b1f', textMuted: '#6b6b76', turn: '#b45309',
    on: { back1: '#a1a1aa', back2: '#6b6b76', front: '#1b1b1f', dot: '#d4d4dc', accent: '#2563eb', bar2: '#6b6b76' },
    pin: {
      '--bg': '#f4f4f6',
      '--bg-panel': '#ffffff',
      '--bg-panel-2': '#ececf1',
      '--row-hover': 'rgba(0, 0, 0, 0.045)',
      '--text': '#1b1b1f',
      '--text-muted': '#5c5c67',
      '--accent': '#2563eb',
      '--accent-dim': '#1d4ed8',
      '--danger': '#dc2626',
      '--danger-soft': '#b91c1c',
      '--success': '#10662d',
      '--heal-color': '#10662d',
      '--pc-color': '#2158c8',
      '--monster-color': '#8f4d09',
      '--badge-bg': '#e0e7ff',
      '--badge-border': '#a5b4fc',
      '--badge-text': '#3730a3',
      '--warn': '#b45309',
      '--miss': '#8f2f2f',
      '--conc': '#6d4bb0',
    },
  },
];

/** The palette a fresh install starts on, and the one the app icon is drawn in. */
export const DEFAULT_PALETTE: PaletteId = 'violet-ink';

export const PALETTE_BY_ID: Record<string, BrandPalette> = Object.fromEntries(
  PALETTES.map((p) => [p.id, p]),
);

/**
 * Theme ids from before the rebrand. `electron` was violet with a gold-ish
 * accent and `dark` was the neutral one, so each maps to its closest heir;
 * `phb` and `light` kept their ids and need no mapping.
 */
export const LEGACY_THEME_MAP: Record<string, PaletteId> = {
  electron: 'arcane-gold',
  dark: 'violet-ink',
};

/** Coerces any stored value to a live palette id. */
export function migrateThemeId(stored: unknown): PaletteId {
  if (typeof stored !== 'string') return DEFAULT_PALETTE;
  if (stored in PALETTE_BY_ID) return stored as PaletteId;
  return LEGACY_THEME_MAP[stored] ?? DEFAULT_PALETTE;
}

/** The window background before the first paint, so launch doesn't flash. */
export function groundFor(theme: unknown): string {
  return PALETTE_BY_ID[migrateThemeId(theme)].ground;
}
